[package]
name = "rooch_bonding_curve"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }

[addresses]
rooch_bonding_curve = "0x9f486eddc27217bf838b61cfdeeb2e454f7e53a56e2dea9b3f8ceb49090f8ba3"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
